<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>NodePunch</RootNamespace>
    <AssemblyName>NodePunch</AssemblyName>
    <Version>1.5.0</Version>
    <Authors>André Rösler</Authors>
    <Product>NodePunch</Product>
    <ApplicationIcon>Resources\nodepunch.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\nodepunch.ico" />
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

</Project>
